### ISSUE TITLE
Delete Task Not working as expected

### ISSUE THREAD

**Issue by Shreyas-Ashtamkar** [suyogrepale/task4_task_tracker#6]
## STORY
- We opened up the home page, and the tasks got loaded with two buttons -> edit and delete
- On clicking Delete on any task, it was not refreshing and in console we had an error
- This error was regarding the task not found 404

**Comment by Shreyas-Ashtamkar** [comment]
## ROOT CAUSE
- On deep diving we found that the issue is not of 404, it was regarding the task id not found in the database.
- This was due to a faulty code push by @suyogrepale, wherein he was trying to call the "deleteTask" function twice -> Once from the HomePage ( under handleDelete ) and once from the TaskItem component itself, under onDelete. 
- This caused a double "delete" call to the database, with the last being blank, thus the db was responding with the Task ID not being found.

**Comment by Shreyas-Ashtamkar** [comment]
## SOLUTION
- The solution is simple, to update the database using the function "deleteTask" only once, from the leaf component -> the TaskItem.
- We need to comment out the code of the "deleteTask" from the Home page.

**Comment by suyogrepale** [comment]
thanks for highlighting the issue
